### ISSUE TITLE
Filters feature is not complete

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#51]
The implement filers screen does not follow the design requirements. 
Some fields are missing, some fields are empty. The customer confirmed that we need to follow the design. 

![Filters](https://user-images.githubusercontent.com/89276920/194136638-1469fac5-e428-4b58-bf3a-243e4b460665.png)

![photo_2022-10-05_21-36-54](https://user-images.githubusercontent.com/89276920/194136566-2c7dcba4-03e4-4366-b847-ea53d6dd8023.jpg)

Also filters does not work at my device. 

**Now:**
Given I selected some filters from the list
When I proceed
Then the app does not apply the filters to the places displayed on the map

**Expected:**
Given I selected some filters from the list
When I proceed
Then the app does applies the filters to the places displayed on the map

@Sheerazzafar pls confirm if the issue is being reproduced from your device.

**Comment by sallarrezaie** [comment]
PRD #8

Pricing is not included in the PRD which is why it wasn't in the API. 

Filter
Type of place
 Hotels & Stays
Restaurants & Bars
Shopping
Other POIs 
City or Zip Code (Text and Selector Existing Places in APP)
 Country (Text and Selector of Existing in Places APP)
 F&F (Text and Selector to choose ALL or Several)
Experience (Text and Selector with Selector to choose several)
 Would Return
 Thumbs Up
Wanna Visit
 To Explore
 F&F List of Places (Checkbox)
Only Visited
Both Visited and Bucket

**Comment by Sheerazzafar** [comment]
Hi @romangorbunovCB 
I have verified this issue and filters are also not working at my end.
Video: https://www.screencast.com/t/wDjqBOQ9V
Cc: @sallarrezaie

**Comment by sallarrezaie** [comment]
@Sheerazzafar, please refer to PRD #8 - it states the following:

As a User type, I would be able to see the feed In reverse chronological order of added places from **_users that I follow._**
If you are **not** following any users that have saved places to one of their lists, you will not get any results.

Can you confirm that you are following Users and they have places in their list? 

CC: @romangorbunovCB

**Comment by Sheerazzafar** [comment]
@sallarrezaie you are right, I have tested in the way you have mentioned above and it works fine!
Thanks for the clarification!
